export const PinataAPIKey = process.env.REACT_APP_PINATA_API_KEY;
export const PinataSecretKey = process.env.REACT_APP_PINATA_API_SECRET;

export const CONTRACT_ADDRESS_CAPX_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_ETHEREUM;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_ETHEREUM;

export const GRAPHAPIURL =
  process.env.REACT_APP_GRAPHAPIURL || "https://api.thegraph.com/subgraphs/shreyas3336/vesting";
export const GRAPHAPIURL_WRAPPED_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_ETHEREUM;
export const GRAPHAPIURL_VESTING_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_ETHEREUM;
export const GRAPHAPIURL_MASTER_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_ETHEREUM;


export const EXPLORER_ETHEREUM = process.env.REACT_APP_EXPLORER_ETHEREUM;
