export const PinataAPIKey = process.env.REACT_APP_PINATA_API_KEY;
export const PinataSecretKey = process.env.REACT_APP_PINATA_API_SECRET;

export const CONTRACT_ADDRESS_CAPX_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_ETHEREUM;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_ETHEREUM;

export const CONTRACT_ADDRESS_CAPX_MATIC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_MATIC;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_MATIC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_MATIC;

export const CONTRACT_ADDRESS_CAPX_BSC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_BSC;
export const CONTRACT_ADDRESS_CAPX_CONTROLLER_BSC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_CONTROLLER_BSC;


export const GRAPHAPIURL =
  process.env.REACT_APP_GRAPHAPIURL ||
  "https://api.thegraph.com/subgraphs/shreyas3336/vesting";
export const GRAPHAPIURL_WRAPPED_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_ETHEREUM;
export const GRAPHAPIURL_VESTING_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_ETHEREUM;
export const GRAPHAPIURL_MASTER_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_ETHEREUM;

export const GRAPHAPIURL_WRAPPED_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_MATIC;
export const GRAPHAPIURL_VESTING_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_MATIC;
export const GRAPHAPIURL_MASTER_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_MATIC;

export const GRAPHAPIURL_WRAPPED_BSC =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_BSC;
export const GRAPHAPIURL_VESTING_BSC =
  process.env.REACT_APP_GRAPHAPIURL_VESTING_BSC;
export const GRAPHAPIURL_MASTER_BSC =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_BSC;

export const EXPLORER_ETHEREUM = process.env.REACT_APP_EXPLORER_ETHEREUM;
export const EXPLORER_BSC = process.env.REACT_APP_EXPLORER_BSC;
export const EXPLORER_MATIC = process.env.REACT_APP_EXPLORER_MATIC;

export const MATIC_CHAIN_ID = process.env.REACT_APP_MATIC_CHAIN_ID;
export const BSC_CHAIN_ID = process.env.REACT_APP_BSC_CHAIN_ID;
export const ETHEREUM_CHAIN_ID = process.env.REACT_APP_ETHEREUM_CHAIN_ID;